In [12]:
from functions import find_csv_files
import pandas as pd

PRIMARY_KEYS = ["order_id", "product_id", "seller_id", "zip_code_prefix", "customer_id"]
DATA_PATH = "/Users/typhaine/Documents/Doc_Gorilla/OpenClassroom--Machine-Learning-Engineer/P4/data"

csv_files = find_csv_files(DATA_PATH)

df1 = pd.read_csv("./data/olist_customers_dataset.csv")

#df2 = pd.read_csv("./data/olist_geolocation_dataset.csv")
df1

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [5]:
for file in csv_files:
    print(pd.read_csv(file).columns.to_list())

['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
['product_category_name', 'product_category_name_english']
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

In [20]:
import pandas as pd
from typing import List

def join_datasets(file_paths: List[str]) -> pd.DataFrame:
    """
    Perform multiple join operations on Olist datasets.
    
    Parameters:
        file_paths (List[str]): List of CSV file paths containing specific Olist datasets.
        
    Returns:
        pd.DataFrame: A DataFrame after performing all the specified joins.
    """
    
    # Step 3: Load CSV files into DataFrames
    dataframes = {}
    for file_path in file_paths:
        key = file_path.split("/")[-1].replace(".csv", "")
        dataframes[key] = pd.read_csv(file_path)
    
    # Step 4: Join datasets
    # Join olist_order_items_dataset to olist_orders_dataset
    merged_df = pd.merge(dataframes['olist_orders_dataset'], dataframes['olist_order_items_dataset'], on='order_id', how='left')
    
    # Join olist_order_payments_dataset to olist_orders_dataset
    merged_df = pd.merge(merged_df, dataframes['olist_order_payments_dataset'], on='order_id', how='left')
    
    # Join olist_order_reviews_dataset to olist_orders_dataset
    merged_df = pd.merge(merged_df, dataframes['olist_order_reviews_dataset'], on='order_id', how='left')
    
    # Join olist_customers_dataset to olist_orders_dataset
    merged_df = pd.merge(merged_df, dataframes['olist_customers_dataset'], on='customer_id', how='left')
    
     #'seller_zip_code_prefix' 'customer_zip_code_prefix'
    
    # Join olist_sellers_dataset to olist_orders_dataset
    merged_df = pd.merge(merged_df, dataframes['olist_sellers_dataset'], on='seller_id', how='left')

        # Join olist_geolocation_dataset to olist_customers_dataset
    merged_df = pd.merge(merged_df, dataframes['olist_geolocation_dataset'], 
                         left_on='seller_zip_code_prefix', 
                         right_on='geolocation_zip_code_prefix', how='left')
    
    return merged_df

result_df = join_datasets(csv_files)

result_df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,...,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,sao paulo,SP,9350.0,maua,SP,9350.0,-23.680114,-46.452454,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,sao paulo,SP,9350.0,maua,SP,9350.0,-23.675223,-46.441038,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,sao paulo,SP,9350.0,maua,SP,9350.0,-23.685712,-46.444796,mauÃ¡,SP
3,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,sao paulo,SP,9350.0,maua,SP,9350.0,-23.679951,-46.448247,maua,SP
4,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,...,sao paulo,SP,9350.0,maua,SP,9350.0,-23.678662,-46.442578,maua,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17094336,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,lapa,PR,14407.0,franca,SP,14407.0,-20.486153,-47.420998,franca,SP
17094337,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,lapa,PR,14407.0,franca,SP,14407.0,-20.475119,-47.414534,franca,SP
17094338,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,lapa,PR,14407.0,franca,SP,14407.0,-20.488723,-47.409148,franca,SP
17094339,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,lapa,PR,14407.0,franca,SP,14407.0,-20.475478,-47.414575,franca,SP
17094340,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,1.0,006619bbed68b000c8ba3f8725d5409e,...,lapa,PR,14407.0,franca,SP,14407.0,-20.509864,-47.427484,franca,SP

In [17]:
result_df.columns.to_list()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value',
 'review_id',
 'review_score',
 'review_comment_title',
 'review_comment_message',
 'review_creation_date',
 'review_answer_timestamp',
 'customer_unique_id',
 'customer_zip_code_prefix',
 'customer_city',
 'customer_state',
 'seller_zip_code_prefix',
 'seller_city',
 'seller_state']

In [4]:

csv_files = find_csv_files(DATA_PATH)
print(csv_files)

['data/olist_sellers_dataset.csv', 'data/product_category_name_translation.csv', 'data/olist_orders_dataset.csv', 'data/olist_order_items_dataset.csv', 'data/olist_customers_dataset.csv', 'data/olist_geolocation_dataset.csv', 'data/olist_order_payments_dataset.csv', 'data/olist_order_reviews_dataset.csv', 'data/olist_products_dataset.csv']

In [9]:
pd.read_csv(csv_files[0])

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP
...,...,...,...,...
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

In [3]:
df2.columns.to_list()

['geolocation_zip_code_prefix',
 'geolocation_lat',
 'geolocation_lng',
 'geolocation_city',
 'geolocation_state']

In [ ]:
df1.merge(df2)