In [1]:
# Importing necessary libraries
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy as sch
from sklearn.decomposition import PCA
from sklearn.preprocessing import QuantileTransformer, MinMaxScaler
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering

from functions import optimize_kmeans, transform_columns, plot_correlation_circle, optimize_dbscan, optimize_agglomerative_clustering, split_dataframe, split_dataframe_by_time

warnings.simplefilter(action='ignore', category=FutureWarning)

# Apply Seaborn's aesthetic parameters to match Matplotlib's style
sns.set()

# Set pandas display option for maximum columns
pd.set_option('display.max_columns', 50)

DATA_PATH = "/Users/typhaine/Documents/Doc_Gorilla/OpenClassroom--Machine-Learning-Engineer/P4/data/"
DATA_LOAD_FILE = DATA_PATH + "data_cleaned_tagged.csv.gz"
SAMPLE_SIZE = 10_000
SPLITS = 9
RANDOM_STATE = 42
COMPONENTS = 3

VARIABLE_COLUMNS = ["Recency", "Frequency", "PaymentInstallments", "TotalPaymentValue", "MeanProductPrice", "NumberOfProductsInOrder"]

df_original = pd.read_csv(DATA_LOAD_FILE)

df_original

,Recency,Frequency,payment_type,PaymentInstallments,TotalPaymentValue,MeanProductPrice,NumberOfProductsInOrder,OrderTimestamp,K-Mean Label
0,1.261282,-5.199338,0.175278,0.079120,0.408736,0.466899,-5.199338,2017-05-16 15:05:35,1
1,0.027604,-5.199338,0.175278,1.352623,1.350698,1.470986,-5.199338,2018-01-12 20:48:24,1
2,-0.814401,-5.199338,0.175278,1.197193,0.505943,0.704981,-5.199338,2018-05-19 16:07:45,1
3,-0.320290,-5.199338,0.175278,-5.199338,0.637709,0.880310,-5.199338,2018-03-13 16:06:38,0
4,-1.411293,-5.199338,0.175278,1.352623,1.077253,1.264066,-5.199338,2018-07-29 09:51:30,1
...,...,...,...,...,...,...,...,...,...
98644,-0.479432,-5.199338,0.175278,1.068522,-0.210191,-0.016310,-5.199338,2018-04-07 15:48:17,1
98645,-0.459820,-5.199338,0.175278,0.397918,0.249889,0.343120,-5.199338,2018-04-04 08:20:22,1
98646,-0.489307,-5.199338,0.175278,0.879040,-0.809413,-0.795322,-5.199338,2018-04-08 20:11:50,1
98647,0.444534,-5.199338,0.175278,0.079120,1.976943,2.069554,-5.199338,2017-11-03 21:08:33,1
98648,0.148584,-5.199338,0.175278,-5.199338,-2.437922,-1.997676,-5.199338,2017-12-19 14:27:23,0

In [10]:
df_splits = split_dataframe_by_time(df = df_original, datetime_col = "OrderTimestamp", n_splits = 4)

In [11]:
from sklearn.metrics import adjusted_rand_score

for key, df in df_splits.items():
    if df.shape[0]>1:
        km_labels = KMeans(n_clusters=3, random_state=RANDOM_STATE, n_init="auto").fit(df[VARIABLE_COLUMNS].values).labels_
        print(adjusted_rand_score(df["K-Mean Label"].values, km_labels))

    #KMeans(n_clusters=3, random_state=RANDOM_STATE, n_init="auto").fit(df_transformed.values).labels_

0.6261808587046502
0.7090207526983358
0.6501246295812516
0.7189572993934632